### ISSUE TITLE
Binary Exponentiation

### ISSUE THREAD

**Issue by coderguy2000** [keshav2002/competitive-programming-problems#10]

**Comment by coderguy2000** [comment]
Brother you have not make as "hacktoberfest-accepted" label due wich i didn't get as accepted pr make

**Comment by coderguy2000** [comment]
if we add code now its accepts in pr ??

or ou can make my 1st issue of primality test of label as "hacktoberfest-accepted"

**Comment by keshav2002** [comment]
try doing what you are saying.
