### ISSUE TITLE
Euclid: GCd of two numbers

### ISSUE THREAD

**Issue by munish0838** [keshav2002/competitive-programming-problems#18]
@keshav2002 ,I would like to contribute the euclid algorithm for finding greatest common divisor of two numbers
This provides an optimised method than standard approach

**Comment by munish0838** [comment]
Hey @keshav2002 , I have added the file and created a pull request, kindly merge it

**Comment by keshav2002** [comment]
Sure

**Comment by munish0838** [comment]
Thanks
