### ISSUE TITLE
Sieve Of Eratosthenes

### ISSUE THREAD

**Issue by adviksinghania** [keshav2002/competitive-programming-problems#22]
Hello @keshav2002 ,
It's a very common problem to find the prime factorization in competitive problems.
I'd like to implement a solution for the algorithm of Sieve of Eratosthenes using Python3. Kindly assign this issue to me for Hacktoberfest 2021.

**Comment by MayankHora** [comment]
Can I try this or its already closed??

**Comment by adviksinghania** [comment]
Sure. You can ask the maintainers and get it assigned.

**Comment by keshav2002** [comment]
-
